service: lawai-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  
  apiGateway:
    binaryMediaTypes:
      - 'application/pdf'
      - 'application/octet-stream'
      - '*/*'
  
  environment:
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    TEXTRACT_ENABLED: ${env:TEXTRACT_ENABLED}
    BEDROCK_ENABLED: ${env:BEDROCK_ENABLED}
    BEDROCK_MODEL: ${env:BEDROCK_MODEL}
    BEDROCK_API_KEY: ${env:BEDROCK_API_KEY}
    COGNITO_AUTO_UPDATE_CLIENT: ${env:COGNITO_AUTO_UPDATE_CLIENT}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
        - s3:GetObjectVersion
      Resource:
        - "arn:aws:s3:::contractfiles1/*"
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::contractfiles1"
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:InitiateAuth
        - cognito-idp:RespondToAuthChallenge
        - cognito-idp:GetUser
        - cognito-idp:SignUp
        - cognito-idp:ConfirmSignUp
        - cognito-idp:ForgotPassword
        - cognito-idp:ConfirmForgotPassword
        - cognito-idp:UpdateUserPoolClient
      Resource:
        - "arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/us-east-1_1kLOdae9J"
        - "arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/us-east-1_1kLOdae9J/*"
    - Effect: Allow
      Action:
        - textract:StartDocumentTextDetection
        - textract:GetDocumentTextDetection
      Resource: "*"
    - Effect: Allow
      Action:
        - bedrock:InvokeModel
      Resource: "*"

functions:
  api:
    handler: lambda-auth.handler
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
    exclude:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

package:
  exclude:
    - node_modules/**
    - .git/**
    - .env
    - README.md
    - .gitignore
  include:
    - node_modules/**
    - lambda.js
    - index.js
    - data/**
    - package.json